name: wheelchair_app
description: Smart Wheelchair Mobile Dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  firebase_database: ^11.1.0        # Realtime Database - live data sync
  firebase_messaging: ^15.1.0       # Push notifications

  # Notifications (local pop-ups even when app is open)
  flutter_local_notifications: ^17.2.0

  # Charts (for vitals history graph)
  fl_chart: ^0.68.0

  # Date/time formatting
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true