// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjy1E9D54OnIBIkd1Ux-aVgdhi2CY7fNU',
    appId: '1:589281653776:web:9a54d72ec94451658a0695',
    messagingSenderId: '589281653776',
    projectId: 'smart-wheelchair-3f92e',
    authDomain: 'smart-wheelchair-3f92e.firebaseapp.com',
    databaseURL: 'https://smart-wheelchair-3f92e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-wheelchair-3f92e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KejQxxWOM-In6fA50aHHzLPTVZPydnI',
    appId: '1:589281653776:android:4429e38eefc8d5b38a0695',
    messagingSenderId: '589281653776',
    projectId: 'smart-wheelchair-3f92e',
    databaseURL: 'https://smart-wheelchair-3f92e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-wheelchair-3f92e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyt57R5nYkYE7aV7zGl1rMRC3R0aoCKYQ',
    appId: '1:589281653776:ios:06a291cad6888ade8a0695',
    messagingSenderId: '589281653776',
    projectId: 'smart-wheelchair-3f92e',
    databaseURL: 'https://smart-wheelchair-3f92e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-wheelchair-3f92e.firebasestorage.app',
    iosBundleId: 'com.example.wheelchairApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyt57R5nYkYE7aV7zGl1rMRC3R0aoCKYQ',
    appId: '1:589281653776:ios:06a291cad6888ade8a0695',
    messagingSenderId: '589281653776',
    projectId: 'smart-wheelchair-3f92e',
    databaseURL: 'https://smart-wheelchair-3f92e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-wheelchair-3f92e.firebasestorage.app',
    iosBundleId: 'com.example.wheelchairApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjy1E9D54OnIBIkd1Ux-aVgdhi2CY7fNU',
    appId: '1:589281653776:web:f349979c6dc9b0558a0695',
    messagingSenderId: '589281653776',
    projectId: 'smart-wheelchair-3f92e',
    authDomain: 'smart-wheelchair-3f92e.firebaseapp.com',
    databaseURL: 'https://smart-wheelchair-3f92e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-wheelchair-3f92e.firebasestorage.app',
  );
}
