import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';                    // Auto-generated by FlutterFire
import 'screens/dashboard_screen.dart';
import 'services/notification_service.dart';

void main() async {
  // This line ensures Flutter's engine is ready before we do anything async.
  // Required whenever you call async code before runApp().
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase — connects the app to your Firebase project.
  // Must happen before any Firebase calls.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Set up local notification channels (for emergency alerts)
  await NotificationService.initialize();

  // Start the app
  runApp(const WheelchairApp());
}

class WheelchairApp extends StatelessWidget {
  const WheelchairApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Wheelchair',
      debugShowCheckedModeBanner: false,   // Remove "debug" banner from top-right
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1565C0),   // Deep blue as primary color
          brightness: Brightness.light,
        ),
        useMaterial3: true,
      ),
      home: const DashboardScreen(),
    );
  }
}