#ifndef ULTRASONIC_PRIVATE_H
#define ULTRASONIC_PRIVATE_H

#include "../../MCAL/REGISTERS/PIC16F877A_reg.h"

/* TRIG Pin — RD0 */
#define ULTRASONIC_TRIG_DIR     TRISD
#define ULTRASONIC_TRIG_PORT    PORTD
#define ULTRASONIC_TRIG_PIN     0

/* ECHO Pin — RB0 (EXTI pin) */
#define ULTRASONIC_ECHO_DIR     TRISB
#define ULTRASONIC_ECHO_PIN     0

#endif